# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Backend
    # =======
    - package-ecosystem: pip
      directory: /backend/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    # Backend (nodejs)
    - package-ecosystem: npm
      directory: /backend/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    # Seeder
    # =======
    - package-ecosystem: npm
      directory: /seeder/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    # Android
    # =======
    - package-ecosystem: pip
      directory: /android/AnimeCore(kivy)/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    # Tools
    # Seeder
    # =======
    - package-ecosystem: pip
      directory: /tools/seeder/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    # Bots
    # =====
    - package-ecosystem: pip
      directory: /bots/discord/
      schedule:
          interval: weekly
      open-pull-requests-limit: 100

    #Frontend
    #- package-ecosystem: 'npm'
    #  directory: '/frontend'
    #  schedule:
    #      interval: 'weekly'

    # Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
