repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.7.0
      hooks:
          - id: django-upgrade
            args: [--target-version, '4.0']
