repos:
    - repo: https://github.com/asottile/dead
      rev: v1.4.0
      hooks:
          - id: dead
          
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.5.0
      hooks:
        -   id: django-upgrade
            args: [--target-version, "4.0"]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
        -   id: prettier

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast

    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ['--profile', 'black']

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.31.1
      hooks:
          - id: pyupgrade
            args: [--py37-plus]
