repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black

    - repo: https://github.com/adamchainz/django-upgrade
      rev: 1.7.0
      hooks:
          - id: django-upgrade
            args: [--target-version, '4.0']

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
          - id: prettier
            files: \.(js|jsx|ts|tsx|css|sass|scss|svelte|html|lock|json)$
            args: ['--ignore-path', './backend/static/**/*']
            additional_dependencies:
                - prettier@2.6.2
                - 'prettier-plugin-svelte@2.7.0'

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-ast

    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            args: ['--profile', 'black']

    - repo: https://github.com/asottile/pyupgrade
      rev: v2.32.1
      hooks:
          - id: pyupgrade
            args: [--py310-plus]
