services:
    db:
        restart: unless-stopped
        image: postgres:15-alpine
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        expose:
            - 5432

    web:
        image: coreproject
        restart: unless-stopped
        build: ./backend
        entrypoint: /code/server_entrypoint.sh
        volumes:
            - ./media:/code/django_core/media
        ports:
            - "9000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - DJANGO_ALLOWED_HOSTS=backend.coreproject.moe
        depends_on:
            - db

    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine

    worker:
        image: coreproject
        restart: unless-stopped
        build: ./backend
        volumes:
            - ./media:/code/django_core/media
        entrypoint: /code/worker_entrypoint.sh
        environment:
            - "REDIS_URL=redis://redis:6379/0"
            - "CELERY_BROKER_URL=redis://redis:6379/0"
            - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - DJANGO_ALLOWED_HOSTS=backend.coreproject.moe
        depends_on:
            - web
            - redis

    # caddy:
    #     image: caddy:2
    #     container_name: caddy
    #     restart: always
    #     ports:
    #         - 80:80 # Needed for the ACME HTTP-01 challenge.
    #         - 443:443
    #     volumes:
    #         - ./Caddyfile:/etc/caddy/Caddyfile:ro
    #         - ./caddy-config:/config
    #         - ./caddy-data:/data
    #     environment:
    #         - SITE_ADDRESS=coreproject.moe
    #         - LOG_FILE=/data/access.log
volumes:
    pgdata:
