[project]
name = "core-backend"
version = "0.1.0"
description = "A modern backend powering the the world's most modern anime site"
authors = [
    {name = "", email = ""},
    {name = "baseplate-admin"},
]
requires-python = ">=3.10,<4.0"
license = {text = "AGPL-3.0-only"}

[tool.pylint.format]
max-line-length = "92"

[tool.mypy]
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "core.settings"


[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
