[project]
name = "core-backend"
version = "0.1.0"
description = "A modern backend powering the the world's most modern anime site"
authors = [
    {name = "", email = ""},
    {name = "baseplate-admin"},
]
requires-python = ">=3.10,<4.0"
license = {text = "AGPL-3.0-only"}
dependencies = [
    "django[argon2]>=4.1",
    "psycopg2>=2.9.3",
    "django-cleanup>=6.0.0",
    "django-cors-headers>=3.13.0",
    "python-dotenv>=0.20.0",
    "django-ckeditor>=6.5.0",
    "whitenoise>=6.2.0",
    "huey>=2.4.3",
    "redis>=4.3.4",
    "hiredis;sys_platform != 'win32'",
    "django-ninja>=0.19.1",
    "requests>=2.28.1",
    "requests-cache>=0.9.5",
    "requests-ratelimiter>=0.3.2",
    "pillow>=9.2.0",
    "discord.py[voice]>=2.0.0",
    "uwsgi;sys_platform != 'win32'"
]
[project.optional-dependencies]


[tool.pdm.build]
includes = []

[tool.pdm.dev-dependencies]
dev = [
    "django-debug-toolbar>=3.6.0",
    "django-dbbackup>=4.0.1",
    "django-cprofile-middleware>=1.0.5",
    "black>=22.6.0",
    "pylint>=2.14.5",
    "pylint-django>=2.5.3",
    "mypy>=0.961",
    "types-requests>=2.28.8",
    "types-redis>=4.3.14",
    "django-stubs[compatible-mypy]>=1.12.0",
]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.mypy]
ignore_missing_imports = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "core.settings"


[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

[tool.pdm.scripts]
dev = 'python manage.py runserver'
sync = 'python manage.py migrate'
mksync = 'python manage.py makemigrations'
collectstatic = 'python manage.py collectstatic --clear --link' # Dont duplicate copy files.
prod = "gunicorn core.asgi:application -w 4 -k uvicorn.workers.UvicornWorker" # For linux only
huey = "python manage.py run_huey"
populate_characters = 'python manage.py populate_characters'
