[project]
name = "core-backend"
version = "0.1.0"
description = "A modern backend powering the the world's most modern anime site"
authors = [
    {name = "baseplate-admin", email = "61817579+baseplate-admin@users.noreply.github.com"},
]
requires-python = ">=3.10,<4.0"
license = {text = "AGPL-3.0-only"}

[tool.pylint.format]
max-line-length = "92"

[tool.black]
line-length = 92
target-version = ['py311']

[tool.mypy]
show_error_codes = true
warn_unreachable = true
strict = true
disallow_any_generics = true
disallow_subclassing_any = true
warn_return_any = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
check_untyped_defs = true
plugins = ["mypy_django_plugin.main"]
exclude = [
    "migrations"
]

[tool.django-stubs]
django_settings_module = "core.settings"


[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
force_grid_wrap = 0
