[project]
name = "core-backend"
version = "0.1.0"
description = "A modern backend powering the the world's most advanced anime site"
authors = [
    {name = "baseplate-admin", email = "61817579+baseplate-admin@users.noreply.github.com"},
]
requires-python = ">=3.11,<4.0"
license = {text = "AGPL-3.0-only"}


[tool.black]
line-length = 92
target-version = ["py311"]

[tool.mypy]
show_error_codes = true
warn_unreachable = true
strict = true
disallow_any_generics = true
disallow_subclassing_any = true
warn_return_any = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
check_untyped_defs = true
follow_imports = "silent"
plugins = ["mypy_django_plugin.main"]
exclude = [
    "migrations"
]
mypy_path = "django_core,tsukaeru"
namespace_packages = true
explicit_package_bases = true

[tool.django-stubs]
django_settings_module = "core.settings"


[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
force_sort_within_sections = true
combine_as_imports = true
force_grid_wrap = 0

sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "DJANGO",
    "AIOHTTP",
    "LOCALFOLDER"
]
known_aiohttp = [
    "aiohttp",
    "aiohttp_client_cache",
    "aiohttp_retry",
    "aiohttp_jinja2"
]
known_django = [
    'django',
    'djclick'
]


[tool.ruff]
line-length = 92

# Exclude a variety of commonly ignored directories.
exclude = [
    "migrations",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]


# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"

[tool.ruff.per-file-ignores]
"*/__init__.py" = ["E402"]
"*/settings.py" = ["E402"]
"*/api_v1.py" = ["E402"]
"*/urls.py" = ['E402']

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
