name: Seeder

on:
  push:
    branches: ["master"]
    # paths: ["seeder/**"]
  pull_request:
    branches: ["master"]
    # paths: ["seeder/**"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout Seeder
        uses: actions/checkout@v4
        with:
          path: ./seeder
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
        working-directory: ./seeder
      - name: Run Build
        run: npm run build
        working-directory: ./seeder

