name: Seeder Build

on:
    push:
        paths:
            - 'seeder/**'
            - '.github/**'
        branches:
            - '*'
    pull_request:
        paths:
            - 'seeder/**'
            - '.github/**'
        branches: ['master']

    workflow_dispatch:

permissions:
    contents: read

jobs:
    linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  sparse-checkout: 'seeder'
                  sparse-checkout-cone-mode: false

            - name: Setup Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.x

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Install python dependencies
              run: |
                  cd seeder
                  poetry install

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
            - run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev
            - name: Flet Build Linux
              run: |
                  cd seeder
                  poetry run flet build linux ./src/seeder_flet --v

    windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  sparse-checkout: 'seeder'
                  sparse-checkout-cone-mode: false

            - name: Setup Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12.x

            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: Install python dependencies
              run: |
                  cd seeder
                  poetry install

            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable

            - name: Flet Build Windows
              run: |
                  cd seeder
                  poetry run flet build windows ./src/seeder_flet --v
